export const permissionGroups = {
  setupRead: ['setup:read', 'reports:read'],
  setupWrite: ['setup:write'],
  shiftsOpen: ['shifts:open'],
  shiftsClose: ['shifts:close'],
  shiftsRead: ['shifts:read'],
  shiftsApprove: ['shifts:approve'],
  salesPos: ['sales:pos'],
  salesRead: ['sales:read'],
  salesVoid: ['sales:void'],
  inventoryRead: ['inventory:read'],
  inventoryWrite: ['inventory:write'],
  inventoryAccess: ['inventory:read', 'inventory:write'],
  deliveriesRead: ['deliveries:read'],
  deliveriesWrite: ['deliveries:write'],
  deliveriesAccess: ['deliveries:read', 'deliveries:write'],
  transfersRead: ['transfers:read'],
  transfersWrite: ['transfers:write'],
  adjustmentsRead: ['adjustments:read'],
  adjustmentsWrite: ['adjustments:write'],
  creditRead: ['credit:read'],
  creditWrite: ['credit:write'],
  payablesRead: ['payables:read'],
  payablesWrite: ['payables:write'],
  expensesRead: ['expenses:read'],
  expensesWrite: ['expenses:write'],
  reportsRead: ['reports:read'],
  reportsRefresh: ['reports:refresh'],
  auditRead: ['audit:read'],
  governanceRead: [
    'setup:read',
    'reports:read',
    'shifts:read',
    'expenses:read',
    'sales:read',
    'deliveries:read',
    'adjustments:read',
  ],
  governanceSubmit: [
    'setup:write',
    'shifts:close',
    'expenses:write',
    'sales:void',
    'adjustments:write',
    'deliveries:write',
  ],
  governanceAct: [
    'shifts:approve',
    'setup:write',
    'expenses:write',
    'sales:void',
    'adjustments:write',
    'deliveries:write',
  ],
  usersAdmin: ['setup:write'],
} satisfies Record<string, string[]>;
