import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHash } from 'node:crypto';
import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import { ReportsService, type ReportPerfContext } from '../reports/reports.service';
import type { ReportsQueryDto } from '../reports/dto/reports-query.dto';
import type { ExportScope, ExportType } from './exports.types';

interface RenderExportArgs {
  exportId: string;
  exportType: string;
  format: 'pdf' | 'csv';
  params: Record<string, unknown>;
  verificationToken: string;
  scope: ExportScope;
  createdAt: Date;
}

interface VerificationReceiptInput {
  exportId: string;
  exportType: string;
  format: 'pdf' | 'csv';
  verificationToken: string;
  verificationLevel: string;
  sha256Hash: string | null;
  generatedAt: Date;
  expiresAt: Date | null;
  signer: string | null;
  certFingerprint: string | null;
  signedAt: Date | null;
  timestampedAt: Date | null;
  tsaProvider: string | null;
}

@Injectable()
export class ExportsRendererService {
  constructor(private readonly reportsService: ReportsService, private readonly config: ConfigService) {}

  async renderExport(args: RenderExportArgs): Promise<{ buffer: Buffer; mimeType: string }> {
    const payload = await this.resolvePayload(args.exportType as ExportType, args.params, args.scope, args.exportId);
    if (args.format === 'csv') {
      const csv = this.buildCsv(args.exportType, payload, args.createdAt);
      return { buffer: Buffer.from(csv, 'utf8'), mimeType: 'text/csv; charset=utf-8' };
    }

    const pdf = await this.buildPdf(args.exportType, payload, args.params, args.exportId, args.verificationToken, args.createdAt);
    return { buffer: pdf, mimeType: 'application/pdf' };
  }

  sha256(buffer: Buffer): string {
    return createHash('sha256').update(buffer).digest('hex');
  }

  async buildVerificationReceiptPdf(input: VerificationReceiptInput): Promise<Buffer> {
    const verifyBase = this.config.get<string>('EXPORT_VERIFY_BASE_URL', 'https://www.itembagroup.llc/public/report/verify');
    const verifyUrl = `${verifyBase}?token=${input.verificationToken}`;
    const qrPng = await QRCode.toBuffer(verifyUrl, { type: 'png', width: 96, margin: 0 });

    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    doc.font('Helvetica-Bold').fontSize(16).text('IFMS EXPORT VERIFICATION RECEIPT', 40, 40);
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(10).fillColor('#111827');
    doc.text(`Reference: ${input.exportId}`);
    doc.text(`Export Type: ${input.exportType}`);
    doc.text(`Format: ${input.format.toUpperCase()}`);
    doc.text(`Verification Level: ${input.verificationLevel}`);
    doc.text(`Generated At: ${input.generatedAt.toISOString()}`);
    doc.text(`Expires At: ${input.expiresAt ? input.expiresAt.toISOString() : 'N/A'}`);
    doc.text(`SHA-256: ${input.sha256Hash ?? 'N/A'}`);
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').text('Signing Details');
    doc.font('Helvetica');
    doc.text(`Signer: ${input.signer ?? 'N/A'}`);
    doc.text(`Signed At: ${input.signedAt ? input.signedAt.toISOString() : 'N/A'}`);
    doc.text(`Certificate Fingerprint: ${input.certFingerprint ?? 'N/A'}`);
    doc.text(`Timestamped At: ${input.timestampedAt ? input.timestampedAt.toISOString() : 'N/A'}`);
    doc.text(`TSA Provider: ${input.tsaProvider ?? 'N/A'}`);
    doc.moveDown(0.8);
    doc.text(`Verify online: ${verifyUrl}`);
    doc.image(qrPng, 40, 290, { fit: [86, 86] });
    doc.font('Helvetica').fontSize(8).text('System-generated by IFMS Legal Document Verification', 40, 790);

    doc.end();
    return await new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  private async resolvePayload(
    exportType: ExportType,
    params: Record<string, unknown>,
    scope: ExportScope,
    exportId: string,
  ): Promise<unknown> {
    if (exportType === 'tables.any') {
      return {
        title: typeof params.title === 'string' ? params.title : 'Table Export',
        columns: Array.isArray(params.columns) ? params.columns : [],
        rows: Array.isArray(params.rows) ? params.rows : [],
      };
    }

    const q = this.toReportsQuery(params);
    const perfCtx: ReportPerfContext = {
      endpoint: `/exports/${exportType}`,
      correlationId: `exp-${exportId}`,
      scope: {
        userId: scope.userId,
        permissions: scope.permissions,
        companyId: q.companyId ?? scope.companyId,
        branchId: q.branchId ?? scope.branchId,
      },
    };

    switch (exportType) {
      case 'reports.overview':
        return this.reportsService.getOverview(q, perfCtx);
      case 'reports.daily-operations':
        return this.reportsService.getDailyOperations(q, perfCtx);
      case 'reports.stock-loss':
        return this.reportsService.getStockLoss(q, perfCtx);
      case 'reports.profitability':
        return this.reportsService.getProfitability(q, perfCtx);
      case 'reports.credit-cashflow':
        return this.reportsService.getCreditCashflow(q, perfCtx);
      case 'reports.station-comparison':
        return this.reportsService.getStationComparison(q, perfCtx);
      default:
        return {};
    }
  }

  private toReportsQuery(params: Record<string, unknown>): ReportsQueryDto {
    const q: ReportsQueryDto = {};
    if (typeof params.dateFrom === 'string') q.dateFrom = params.dateFrom;
    if (typeof params.dateTo === 'string') q.dateTo = params.dateTo;
    if (typeof params.companyId === 'string') q.companyId = params.companyId;
    if (typeof params.stationId === 'string') q.stationId = params.stationId;
    if (typeof params.branchId === 'string') q.branchId = params.branchId;
    if (typeof params.productId === 'string') q.productId = params.productId;
    return q;
  }

  private buildCsv(exportType: string, payload: unknown, generatedAt: Date): string {
    const rows: string[] = [];
    const dataHash = this.sha256(Buffer.from(JSON.stringify(payload), 'utf8'));
    rows.push(`# exportType=${exportType}`);
    rows.push(`# generatedAt=${generatedAt.toISOString()}`);
    rows.push(`# sha256=${dataHash}`);

    if (exportType === 'tables.any' && payload && typeof payload === 'object') {
      const typed = payload as { columns?: Array<{ header: string; accessorKey: string }>; rows?: Array<Record<string, unknown>> };
      const headers = (typed.columns ?? []).map((c) => c.header);
      const keys = (typed.columns ?? []).map((c) => c.accessorKey);
      rows.push(this.csvLine(headers));
      for (const row of typed.rows ?? []) {
        rows.push(this.csvLine(keys.map((k) => this.toCell(row[k]))));
      }
      return rows.join('\n');
    }

    rows.push('section,key,value');
    this.flattenForCsv(payload).forEach((r) => rows.push(this.csvLine(r)));
    return rows.join('\n');
  }

  private flattenForCsv(payload: unknown): string[][] {
    const out: string[][] = [];
    if (!payload || typeof payload !== 'object') return [['root', 'value', this.toCell(payload)]];
    for (const [key, value] of Object.entries(payload as Record<string, unknown>)) {
      if (Array.isArray(value)) {
        value.forEach((item, idx) => out.push([key, String(idx), this.toCell(item)]));
      } else if (value && typeof value === 'object') {
        for (const [k2, v2] of Object.entries(value as Record<string, unknown>)) {
          out.push([key, k2, this.toCell(v2)]);
        }
      } else {
        out.push(['summary', key, this.toCell(value)]);
      }
    }
    return out;
  }

  private csvLine(values: Array<string | number>): string {
    return values
      .map((value) => {
        const str = String(value ?? '');
        if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
          return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
      })
      .join(',');
  }

  private toCell(value: unknown): string {
    if (value == null) return '';
    if (typeof value === 'string') return value;
    if (typeof value === 'number' || typeof value === 'boolean') return String(value);
    return JSON.stringify(value);
  }

  private async buildPdf(
    exportType: string,
    payload: unknown,
    params: Record<string, unknown>,
    exportId: string,
    verificationToken: string,
    generatedAt: Date,
  ): Promise<Buffer> {
    const verifyBase = this.config.get<string>('EXPORT_VERIFY_BASE_URL', 'https://www.itembagroup.llc/public/report/verify');
    const verifyUrl = `${verifyBase}?token=${verificationToken}`;
    const qrPng = await QRCode.toBuffer(verifyUrl, { type: 'png', width: 96, margin: 0 });
    const dataDigest = this.sha256(Buffer.from(JSON.stringify(payload), 'utf8')).slice(0, 12);

    const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const drawHeader = () => {
      doc.font('Helvetica-Bold').fontSize(10).text('[ITEMBA-ENERGIES LOGO]', 40, 30);
      doc.font('Helvetica-Bold').fontSize(14).text('ITEMBA-ENERGIES', 40, 45);
      doc.font('Helvetica').fontSize(10).text('Fuel Operations & Intelligence', 40, 62);

      const right = [
        'ITEMBA-ENERGIES',
        'A Division of Itemba Group',
        'Tunduma, Songwe, Tanzania',
        'Tel: +255758793511',
        'Email: itembaenergies@itembagroup.llc',
        'Website: www.itembagroup.llc',
        'TIN: 116-321-378  •  VRN: 40-012813-B',
      ];

      doc.font('Helvetica').fontSize(9).text(right.join('\n'), 330, 30, { width: 220, align: 'right' });
      doc
        .moveTo(40, 102)
        .lineTo(555, 102)
        .lineWidth(1)
        .strokeColor('#1d4ed8')
        .stroke();
    };

    const drawTitleBlock = () => {
      const period = `${String(params.dateFrom ?? 'N/A')} – ${String(params.dateTo ?? 'N/A')}`;
      const scope = `${String(params.companyId ?? 'company')} / ${String(params.stationId ?? 'station')} / ${String(params.branchId ?? 'branch')}`;
      doc.font('Helvetica-Bold').fontSize(15).text(exportType.replace('reports.', '').toUpperCase(), 40, 118);
      doc.font('Helvetica').fontSize(10).text(`Reporting Period: ${period}`, 40, 140);
      doc.font('Helvetica').fontSize(10).text(`Scope: ${scope}`, 40, 156);
      doc
        .font('Helvetica')
        .fontSize(10)
        .text(`Generated: ${generatedAt.toISOString()} (Africa/Dar_es_Salaam)`, 40, 172);
      doc.font('Helvetica').fontSize(10).text(`Reference: ${exportId.slice(0, 8)}`, 40, 188);
    };

    drawHeader();
    drawTitleBlock();

    const pretty = JSON.stringify(payload, null, 2).split('\n');
    doc.font('Courier').fontSize(8);
    let y = 218;
    for (const line of pretty) {
      if (y > 760) {
        doc.addPage();
        drawHeader();
        y = 120;
      }
      doc.text(line, 40, y, { width: 515 });
      y += 11;
    }

    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i += 1) {
      doc.switchToPage(i);
      const pageNumber = i + 1;
      doc.font('Helvetica').fontSize(8).fillColor('#111827').text('System-generated by IFMS • Confidential', 40, 802, { width: 170, align: 'left' });
      doc.font('Helvetica').fontSize(8).text('Digitally Signed (PAdES)', 40, 790, { width: 170, align: 'left' });
      doc.font('Helvetica').fontSize(8).text('Trusted Timestamp (RFC3161)', 220, 790, { width: 170, align: 'center' });
      doc.font('Helvetica').fontSize(8).text(`SHA-256: ${dataDigest}…`, 220, 802, { width: 130, align: 'center' });
      doc.image(qrPng, 470, 786, { fit: [26, 26] });
      doc.font('Helvetica').fontSize(8).text('Verify', 500, 793, { width: 40 });
      doc.font('Helvetica').fontSize(8).text(`Page ${pageNumber} of ${range.count}`, 510, 806, { width: 45, align: 'right' });
    }

    doc.switchToPage(range.count - 1);
    const signerLabel = this.config.get<string>('SIGNING_ORG_DISPLAY', 'ITEMBA-ENERGIES (IFMS)');
    doc
      .rect(40, 730, 380, 58)
      .lineWidth(0.6)
      .strokeColor('#9ca3af')
      .stroke();
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#111827').text('Signature Panel', 46, 736);
    doc.font('Helvetica').fontSize(8).text(`Signed by: ${signerLabel}`, 46, 748);
    doc.font('Helvetica').fontSize(8).text('Signed at: pending timestamp', 46, 760);
    doc.font('Helvetica').fontSize(8).text('Certificate fingerprint: pending', 46, 772);
    doc.font('Helvetica').fontSize(8).text(`Verification URL: ${verifyUrl}`, 46, 784, { width: 366 });

    doc.end();

    return await new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }
}
